name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  workflow_dispatch: 
    inputs:
      name:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "prepare env"
      - run: sudo apt update -y
      - run: sudo apt full-upgrade -y
      - run: sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib  g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev  libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5 libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool lld llvm lrzsz mkisofs msmtp   nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip python3-ply  python3-docutils python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig  texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
